import type { VSCodeTheme } from '../types';

export const modularDark: VSCodeTheme = {
    name: 'Modular Dark',
    type: 'dark',
    colors: {
        'editor.background': '#0a0a0a',
        'editor.foreground': '#cccccc',
        'editor.lineHighlightBackground': '#111111',
        'editor.selectionBackground': '#2d6b5f',
        'editor.inactiveSelectionBackground': '#1f3a3a',
        'editorCursor.foreground': '#4ec9b0',
        'editorLineNumber.foreground': '#555555',
        'editorLineNumber.activeForeground': '#888888',
        'editorIndentGuide.background': '#222222',
        'editorIndentGuide.activeBackground': '#2a2a2a',
        'editorWhitespace.foreground': '#222222',
        'editorBracketMatch.background': '#2d6b5f44',
        'editorBracketMatch.border': '#4ec9b0',
        'editorGutter.background': '#0a0a0a',
        'editorWidget.background': '#111111',
        'editorWidget.border': '#222222',
        'editorSuggestWidget.background': '#111111',
        'editorSuggestWidget.border': '#222222',
        'editorSuggestWidget.foreground': '#cccccc',
        'editorSuggestWidget.selectedBackground': '#1f3a3a',
        'editorHoverWidget.background': '#111111',
        'editorHoverWidget.border': '#222222',
        
        'activityBar.background': '#0a0a0a',
        'activityBar.foreground': '#cccccc',
        'sideBar.background': '#111111',
        'sideBar.foreground': '#cccccc',
        'sideBar.border': '#222222',
        'sideBarSectionHeader.background': '#161616',
        'sideBarSectionHeader.foreground': '#888888',
        
        'statusBar.background': '#111111',
        'statusBar.foreground': '#888888',
        
        'tab.activeBackground': '#0a0a0a',
        'tab.inactiveBackground': '#111111',
        'tab.activeForeground': '#cccccc',
        'tab.inactiveForeground': '#888888',
        'tab.border': '#222222',
        
        'list.activeSelectionBackground': '#1f3a3a',
        'list.activeSelectionForeground': '#4ec9b0',
        'list.hoverBackground': '#1a1a1a',
        'list.focusBackground': '#1f3a3a',
        
        'input.background': '#111111',
        'input.foreground': '#cccccc',
        'input.border': '#2a2a2a',
        'input.placeholderForeground': '#555555',
        
        'button.background': '#2d6b5f',
        'button.foreground': '#ffffff',
        'button.hoverBackground': '#3d7b6f',
        
        'focusBorder': '#4ec9b0',
        'foreground': '#cccccc',
        'descriptionForeground': '#888888',
        'disabledForeground': '#555555',
        
        'scrollbar.shadow': '#00000000',
        'scrollbarSlider.background': '#2a2a2a',
        'scrollbarSlider.hoverBackground': '#555555',
        'scrollbarSlider.activeBackground': '#555555',
        
        'terminal.ansiGreen': '#3fb27f',
        'terminal.ansiYellow': '#d4a855',
        'terminal.ansiRed': '#e05561',
        'terminal.ansiBlue': '#61afef',
        'terminal.ansiCyan': '#5ce1e6',
        'terminal.ansiMagenta': '#c678dd',
    },
    tokenColors: [
        { scope: ['comment'], settings: { foreground: '#555555', fontStyle: 'italic' } },
        { scope: ['keyword', 'storage.type', 'storage.modifier'], settings: { foreground: '#4ec9b0' } },
        { scope: ['string', 'string.quoted'], settings: { foreground: '#d4a855' } },
        { scope: ['constant.numeric', 'constant.language'], settings: { foreground: '#5ce1e6' } },
        { scope: ['entity.name.function', 'support.function'], settings: { foreground: '#61afef' } },
        { scope: ['variable', 'variable.other'], settings: { foreground: '#cccccc' } },
        { scope: ['entity.name.type', 'support.type'], settings: { foreground: '#4ec9b0' } },
        { scope: ['punctuation', 'meta.brace'], settings: { foreground: '#888888' } },
        { scope: ['constant.other', 'variable.other.constant'], settings: { foreground: '#5ce1e6' } },
    ],
};
