// AUTOGENERATED FILE
// This file was generated from mini.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface MusicalDSLActionDict<T> extends BaseActionDict<T> {
  Program?: (this: NonterminalNode, arg0: IterationNode) => T;
  Element?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  NonRandomElement?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  FastSubsequence?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  SlowSubsequence?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  RandomChoice?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: IterationNode) => T;
  Value?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Rest?: (this: NonterminalNode, arg0: TerminalNode) => T;
  HzValue?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode, arg2: IterationNode, arg3: IterationNode, arg4: TerminalNode) => T;
  NumericLiteral?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode, arg2: IterationNode, arg3: IterationNode) => T;
  NoteName?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: IterationNode) => T;
  MidiValue?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode) => T;
  accidental?: (this: NonterminalNode, arg0: TerminalNode) => T;
}

export interface MusicalDSLSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: MusicalDSLActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: MusicalDSLActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: MusicalDSLActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: MusicalDSLActionDict<T>): this;
}

export interface MusicalDSLGrammar extends Grammar {
  createSemantics(): MusicalDSLSemantics;
  extendSemantics(superSemantics: MusicalDSLSemantics): MusicalDSLSemantics;
}

declare const grammar: MusicalDSLGrammar;
export default grammar;

