import {
    BrowserWindow,
    Menu,
    MenuItem,
    app,
    autoUpdater,
    dialog,
    globalShortcut,
    ipcMain,
    shell,
} from 'electron';
import type { PatchGraph, AudioConfigOptions } from '@modular/core';
import { getMiniLeafSpans, Synthesizer } from '@modular/core';
import schemas from '@modular/core/schemas.json';
import type {
    IPCHandlers,
    FileTreeEntry,
    ContextMenuOptions,
    DSLExecuteResult,
    MainLogLevel,
    MainLogEntry,
    UpdateAvailableInfo,
} from '../shared/ipcTypes';
import { IPC_CHANNELS, MENU_CHANNELS } from '../shared/ipcTypes';
import { reconcilePatchBySimilarity } from './patchSimilarityRemap';
import { executePatchScript } from './dsl/executor';
import { buildLibSource } from './dsl/typescriptLibGen';
import * as fs from 'fs';
import * as path from 'path';
import electronSquirrelStartup from 'electron-squirrel-startup';
import { z } from 'zod';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// Plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// Whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Declare mainWindow early so log forwarding can reference it
let mainWindow: BrowserWindow | null = null;

// ========================================================================
// Main Process Log Forwarding
// ========================================================================
// Queue logs until the renderer is ready, then forward all logs to renderer
const pendingLogEntries: MainLogEntry[] = [];
let rendererReady = false;

function sendLogToRenderer(entry: MainLogEntry) {
    if (mainWindow && !mainWindow.isDestroyed() && rendererReady) {
        mainWindow.webContents.send(IPC_CHANNELS.MAIN_LOG, entry);
    } else {
        // Queue log entries until renderer is ready
        pendingLogEntries.push(entry);
    }
}

function flushPendingLogs() {
    if (mainWindow && !mainWindow.isDestroyed()) {
        rendererReady = true;
        for (const entry of pendingLogEntries) {
            mainWindow.webContents.send(IPC_CHANNELS.MAIN_LOG, entry);
        }
        pendingLogEntries.length = 0;
    }
}

// Intercept console methods to forward to renderer
const originalConsole = {
    debug: console.debug.bind(console),
    error: console.error.bind(console),
    info: console.info.bind(console),
    log: console.log.bind(console),
    warn: console.warn.bind(console),
};

function createLogInterceptor(level: MainLogLevel) {
    return (...args: unknown[]) => {
        // Always call original console method first
        originalConsole[level](...args);

        // Forward to renderer (serialize args to handle non-transferable values)
        const entry: MainLogEntry = {
            args: args.map((arg) => serializeForIPC(arg)),
            level,
            timestamp: Date.now(),
        };
        sendLogToRenderer(entry);
    };
}

/**
 * Serialize a value for IPC transfer, handling non-transferable types
 */
function serializeForIPC(
    value: unknown,
    seen = new WeakSet<object>(),
): unknown {
    // Handle primitives
    if (value === null || value === undefined) {
        return value;
    }

    if (
        typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean'
    ) {
        return value;
    }

    // Handle BigInt by converting to string with 'n' suffix for clarity
    if (typeof value === 'bigint') {
        return `${value}n`;
    }

    // Handle symbols
    if (typeof value === 'symbol') {
        return value.toString();
    }

    // Handle functions
    if (typeof value === 'function') {
        return `[Function: ${value.name || 'anonymous'}]`;
    }

    // Handle Error objects specially
    if (value instanceof Error) {
        return {
            __error: true,
            message: value.message,
            name: value.name,
            stack: value.stack,
        };
    }

    // Handle objects and arrays
    if (typeof value === 'object') {
        // Detect circular references
        if (seen.has(value)) {
            return '[Circular]';
        }
        seen.add(value);

        // Handle arrays
        if (Array.isArray(value)) {
            return value.map((item) => serializeForIPC(item, seen));
        }

        // Handle Date
        if (value instanceof Date) {
            return value.toISOString();
        }

        // Handle Map
        if (value instanceof Map) {
            const obj: Record<string, unknown> = { __type: 'Map' };
            for (const [k, v] of value) {
                obj[String(k)] = serializeForIPC(v, seen);
            }
            return obj;
        }

        // Handle Set
        if (value instanceof Set) {
            return {
                __type: 'Set',
                values: Array.from(value).map((v) => serializeForIPC(v, seen)),
            };
        }

        // Handle plain objects
        const result: Record<string, unknown> = {};
        for (const key of Object.keys(value)) {
            result[key] = serializeForIPC(
                (value as Record<string, unknown>)[key],
                seen,
            );
        }
        return result;
    }

    // Fallback (should be unreachable; all types handled above)
    return JSON.stringify(value);
}

console.log = createLogInterceptor('log');
console.info = createLogInterceptor('info');
console.warn = createLogInterceptor('warn');
console.error = createLogInterceptor('error');
console.debug = createLogInterceptor('debug');

// ========================================================================
// Update Service
// ========================================================================

const GITHUB_REPO = 'HelveticaScenario/operator';
const UPDATE_FEED_URL = `https://update.electronjs.org/${GITHUB_REPO}`;
const GITHUB_API_URL = `https://api.github.com/repos/${GITHUB_REPO}/releases/latest`;

/** True on platforms where autoUpdater (Squirrel) is supported */
const supportsAutoUpdater =
    process.platform === 'darwin' || process.platform === 'win32';

/**
 * Latest release URL from the GitHub API check, stored so the Linux
 * fallback in UPDATE_DOWNLOAD can open it in the browser.
 */
let latestReleaseUrl: string | null = null;

function sendUpdateEvent(channel: string, ...args: unknown[]) {
    if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send(channel, ...args);
    }
}

/**
 * Fetches the latest release from GitHub API and pushes UPDATE_AVAILABLE
 * to the renderer if a newer version is available and not skipped.
 * Does NOT trigger any download.
 */
async function checkForUpdateAvailability(): Promise<void> {
    try {
        const response = await fetch(GITHUB_API_URL, {
            headers: { 'User-Agent': GITHUB_REPO },
        });
        if (!response.ok) {
            console.warn('[update] GitHub API returned', response.status);
            return;
        }
        const ReleaseSchema = z.object({
            html_url: z.string(),
            tag_name: z.string(),
        });
        const parsed = ReleaseSchema.safeParse(await response.json());
        if (!parsed.success) {
            console.warn('[update] Unexpected GitHub API response shape');
            return;
        }
        const latestVersion = parsed.data.tag_name.replace(/^v/, '');
        const currentVersion = app.getVersion();
        if (latestVersion === currentVersion) {
            return;
        }

        // Compare semver — only notify if latest is strictly newer
        const [lMaj, lMin, lPat] = latestVersion.split('.').map(Number);
        const [cMaj, cMin, cPat] = currentVersion.split('.').map(Number);
        // NaN from non-numeric components (e.g. pre-release tags like "1.0.0-beta.1")
        // Causes all comparisons to be false — pre-releases are silently ignored.
        const isNewer =
            lMaj > cMaj ||
            (lMaj === cMaj && lMin > cMin) ||
            (lMaj === cMaj && lMin === cMin && lPat > cPat);

        if (!isNewer) {
            return;
        }

        // Check if this version was skipped
        const config = loadConfig();
        if (config.skippedUpdateVersion === latestVersion) {
            return;
        }

        latestReleaseUrl = parsed.data.html_url;

        const info: UpdateAvailableInfo = {
            releaseUrl: parsed.data.html_url,
            supportsInAppUpdate: supportsAutoUpdater,
            version: latestVersion,
        };
        sendUpdateEvent(IPC_CHANNELS.UPDATE_AVAILABLE, info);
    } catch (err) {
        console.warn('[update] Version check failed:', err);
    }
}

/**
 * Initialise the autoUpdater feed URL and event listeners.
 * Called once, after app.ready, only in packaged builds on supported platforms.
 */
function initAutoUpdater(): void {
    if (!supportsAutoUpdater) {
        return;
    }

    // Update.electronjs.org maps plain "darwin" to "darwin-x64", so we must
    // Include the arch explicitly so it serves the arm64 asset on Apple Silicon.
    const feedPlatform =
        process.platform === 'darwin'
            ? `darwin-${process.arch}` // E.g. "darwin-arm64" or "darwin-x64"
            : process.platform;
    autoUpdater.setFeedURL({
        url: `${UPDATE_FEED_URL}/${feedPlatform}/${app.getVersion()}`,
    });

    autoUpdater.on('update-downloaded', () => {
        sendUpdateEvent(IPC_CHANNELS.UPDATE_DOWNLOADED);
    });

    autoUpdater.on('update-not-available', () => {
        sendUpdateEvent(
            IPC_CHANNELS.UPDATE_ERROR,
            'Update no longer available',
        );
    });

    autoUpdater.on('error', (err: Error) => {
        console.error('[update] autoUpdater error:', err.message);
        sendUpdateEvent(IPC_CHANNELS.UPDATE_ERROR, err.message);
    });
}

// ========================================================================

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (electronSquirrelStartup) {
    app.quit();
}

// Enforce single instance
const gotTheLock = app.requestSingleInstanceLock();
if (!gotTheLock) {
    app.quit();
} else {
    app.on('second-instance', () => {
        // Focus the existing window if someone tries to open a second instance
        const windows = BrowserWindow.getAllWindows();
        if (windows.length > 0) {
            const existingWindow = windows[0];
            if (existingWindow.isMinimized()) {
                existingWindow.restore();
            }
            existingWindow.focus();
        }
    });
}

// Config persistence - defined early so we can load before synth creation
let CONFIG_FILE: string;
try {
    CONFIG_FILE = path.join(app.getPath('userData'), 'config.json');
} catch (error) {
    console.error('Error determining config file path:', error);
    CONFIG_FILE = 'config.json';
}

const AppConfigSchema = z.object({
    audioConfig: z
        .object({
            hostId: z.string().optional(),
            inputDeviceId: z.string().nullable().optional(),
            outputDeviceId: z.string().optional(),
            sampleRate: z.number().optional(),
            bufferSize: z.number().optional(),
        })
        .optional(),
    cursorStyle: z
        .enum([
            'line',
            'block',
            'underline',
            'line-thin',
            'block-outline',
            'underline-thin',
        ])
        .optional(),
    font: z
        .enum([
            // Bundled fonts
            'Fira Code',
            'JetBrains Mono',
            'Cascadia Code',
            'Source Code Pro',
            'IBM Plex Mono',
            'Hack',
            'Inconsolata',
            'Monaspace Neon',
            'Monaspace Argon',
            'Monaspace Xenon',
            'Monaspace Krypton',
            'Monaspace Radon',
            'Geist Mono',
            'Iosevka',
            'Victor Mono',
            'Roboto Mono',
            'Maple Mono',
            'Commit Mono',
            '0xProto',
            'Intel One Mono',
            'Mononoki',
            'Anonymous Pro',
            'Recursive',
            // System fonts (available only if installed)
            'SF Mono',
            'Monaco',
            'Menlo',
            'Consolas',
        ])
        .optional(),
    fontLigatures: z.boolean().optional(),
    fontSize: z.number().min(8).max(72).optional(),
    lastOpenedFolder: z.string().optional(),
    prettier: z.record(z.string(), z.unknown()).optional(),
    skippedUpdateVersion: z.string().optional(),
    theme: z.string().optional(),
});

type AppConfig = z.infer<typeof AppConfigSchema>;

function loadConfig(): AppConfig {
    try {
        if (fs.existsSync(CONFIG_FILE)) {
            const data = fs.readFileSync(CONFIG_FILE, 'utf-8');
            const json = JSON.parse(data);
            const result = AppConfigSchema.safeParse(json);
            if (result.success) {
                return result.data;
            }
            console.error('Config validation failed:', result.error);
        }
    } catch (error) {
        console.error('Error loading config:', error);
    }
    return {};
}

function saveConfig(config: AppConfig) {
    try {
        fs.writeFileSync(CONFIG_FILE, JSON.stringify(config, null, 2), 'utf-8');
    } catch (error) {
        console.error('Error saving config:', error);
    }
}

// Load saved config to pass to synthesizer
const savedConfig = loadConfig();
const audioConfigOptions: AudioConfigOptions | undefined =
    savedConfig.audioConfig
        ? {
              bufferSize: savedConfig.audioConfig.bufferSize ?? undefined,
              hostId: savedConfig.audioConfig.hostId ?? undefined,
              inputDeviceId: savedConfig.audioConfig.inputDeviceId ?? undefined,
              outputDeviceId:
                  savedConfig.audioConfig.outputDeviceId ?? undefined,
              sampleRate: savedConfig.audioConfig.sampleRate ?? undefined,
          }
        : undefined;

// Initialize the synthesizer instance with saved config
console.log('Initializing Synthesizer with config:', audioConfigOptions);
const synth = new Synthesizer(audioConfigOptions);

// Get the actual audio state after construction (may have fallen back to defaults)
const actualAudioState = synth.getCurrentAudioState();
console.log('Actual audio state after construction:', actualAudioState);

// Check for fallback warning and update saved config if devices changed
if (actualAudioState.fallbackWarning) {
    console.warn(
        'Audio device fallback occurred:',
        actualAudioState.fallbackWarning,
    );
}

// Update saved config with actual devices used (in case of fallback)
const actualConfig = loadConfig();
const configNeedsUpdate =
    actualConfig.audioConfig?.hostId !== actualAudioState.hostId ||
    actualConfig.audioConfig?.outputDeviceId !==
        actualAudioState.outputDeviceId ||
    actualConfig.audioConfig?.inputDeviceId !==
        actualAudioState.inputDeviceId ||
    actualConfig.audioConfig?.sampleRate !== actualAudioState.sampleRate ||
    actualConfig.audioConfig?.bufferSize !== actualAudioState.bufferSize;

if (configNeedsUpdate) {
    actualConfig.audioConfig = {
        bufferSize: actualAudioState.bufferSize ?? undefined,
        hostId: actualAudioState.hostId,
        inputDeviceId: actualAudioState.inputDeviceId ?? null,
        outputDeviceId: actualAudioState.outputDeviceId ?? undefined,
        sampleRate: actualAudioState.sampleRate,
    };
    saveConfig(actualConfig);
    console.log('Saved updated audio config after fallback');
}

// Save audio configuration to config file
function saveAudioConfig() {
    try {
        const config = loadConfig();
        const state = synth.getCurrentAudioState();

        config.audioConfig = {
            bufferSize: state.bufferSize ?? undefined,
            hostId: state.hostId,
            inputDeviceId: state.inputDeviceId ?? null,
            outputDeviceId: state.outputDeviceId ?? undefined,
            sampleRate: state.sampleRate,
        };

        saveConfig(config);
        console.log('Audio configuration saved');
    } catch (error) {
        console.error('Error saving audio config:', error);
    }
}

setInterval(() => {
    // Keep the audio thread alive
    console.log('health:', synth.getHealth());
}, 10000);

// Workspace root state
let currentWorkspaceRoot: string | null = null;

// File watcher for config changes
let configWatcher: fs.FSWatcher | null = null;

function ensureConfigExists() {
    if (!fs.existsSync(CONFIG_FILE)) {
        const defaultConfig: AppConfig = {
            cursorStyle: 'block',
            font: 'Fira Code',
            fontSize: 17,
            theme: 'modular-dark',
        };
        saveConfig(defaultConfig);
    }
}

function startConfigWatcher() {
    if (configWatcher) {
        configWatcher.close();
    }

    ensureConfigExists();

    // Watch for config file changes
    configWatcher = fs.watch(CONFIG_FILE, (eventType) => {
        if (eventType === 'change') {
            const config = loadConfig();
            // Send updated config to renderer
            if (mainWindow && !mainWindow.isDestroyed()) {
                mainWindow.webContents.send(
                    IPC_CHANNELS.CONFIG_ON_CHANGE,
                    config,
                );
            }
        }
    });
}

// Patch reconciliation state (reset when a different file/buffer is evaluated)
let lastAppliedPatchGraph: PatchGraph | null = null;
let lastAppliedSourceId: string | null = null;

const DEBUG_LOG =
    process.env.MODULAR_DEBUG_LOG === '1' ||
    process.env.MODULAR_DEBUG_LOG === 'true';

const PATCH_REMAP_THRESHOLD = process.env.MODULAR_PATCH_REMAP_THRESHOLD
    ? Number(process.env.MODULAR_PATCH_REMAP_THRESHOLD)
    : undefined;
const PATCH_REMAP_MARGIN = process.env.MODULAR_PATCH_REMAP_MARGIN
    ? Number(process.env.MODULAR_PATCH_REMAP_MARGIN)
    : undefined;

console.log('Patch remap debug mode:', DEBUG_LOG);

/**
 * Validate that a path is valid (absolute or relative to workspace)
 */
function validatePathInWorkspace(filePath: string): string | null {
    if (path.isAbsolute(filePath)) {
        return filePath;
    }

    if (!currentWorkspaceRoot) {
        return null;
    }

    return path.resolve(currentWorkspaceRoot, filePath);
}

/**
 * Check if a file should be included (only .js and .mjs files)
 */
function isJavaScriptFile(filename: string): boolean {
    return filename.endsWith('.js') || filename.endsWith('.mjs');
}

/**
 * Recursively build file tree for JavaScript files
 */
function buildFileTree(
    dirPath: string,
    relativePath: string = '',
): FileTreeEntry[] {
    const entries: FileTreeEntry[] = [];

    try {
        const items = fs.readdirSync(dirPath, { withFileTypes: true });

        for (const item of items) {
            // Skip hidden files and node_modules
            if (item.name.startsWith('.') || item.name === 'node_modules') {
                continue;
            }

            const itemRelativePath = relativePath
                ? `${relativePath}/${item.name}`
                : item.name;
            const itemAbsolutePath = path.join(dirPath, item.name);

            if (item.isDirectory()) {
                const children = buildFileTree(
                    itemAbsolutePath,
                    itemRelativePath,
                );
                if (children.length > 0) {
                    entries.push({
                        children,
                        name: item.name,
                        path: itemRelativePath,
                        type: 'directory',
                    });
                }
            } else if (item.isFile() && isJavaScriptFile(item.name)) {
                entries.push({
                    name: item.name,
                    path: itemRelativePath,
                    type: 'file',
                });
            }
        }
    } catch (error) {
        console.error('Error reading directory:', dirPath, error);
    }

    // Sort: directories first, then files, alphabetically
    return entries.sort((a, b) => {
        if (a.type !== b.type) {
            return a.type === 'directory' ? -1 : 1;
        }
        return a.name.localeCompare(b.name);
    });
}

/**
 * Type-safe IPC handler registration
 */
function registerIPCHandler<T extends keyof typeof IPC_CHANNELS>(
    channel: T,
    handler: IPCHandlers[(typeof IPC_CHANNELS)[T]],
) {
    ipcMain.handle(IPC_CHANNELS[channel], async (_event, ...args) => {
        try {
            // @ts-expect-error - TypeScript has trouble with the variadic handler signatures
            const ret = handler(...args);
            if (ret instanceof Promise) {
                return await ret;
            }
            return ret;
        } catch (error) {
            console.error(`Error in IPC handler ${channel}:`, error);
            throw error;
        }
    });
}

// Register all IPC handlers
// Note: do this instead of importing schemas in renderer to avoid hot-reloading schema changes before
// Main process has restarted with the updated native module.
registerIPCHandler('GET_SCHEMAS', () => schemas);

// DSL lib source for Monaco autocomplete - cached since schemas don't change at runtime
let cachedLibSource: string | null = null;
registerIPCHandler('GET_DSL_LIB_SOURCE', () => {
    if (!cachedLibSource) {
        cachedLibSource = buildLibSource(schemas);
    }
    return cachedLibSource;
});

// DSL execution in main process with direct N-API access
registerIPCHandler(
    'DSL_EXECUTE',
    (source, sourceId, trigger): DSLExecuteResult => {
        try {
            const {
                patch,
                sourceLocationMap,
                interpolationResolutions,
                sliders,
                callSiteSpans,
            } = executePatchScript(source, schemas, {
                sampleRate: synth.sampleRate(),
                workspaceRoot: currentWorkspaceRoot,
            });
            patch.moduleIdRemaps = [];

            // Convert Map to Record for IPC serialization
            const sourceLocationRecord: Record<
                string,
                { line: number; column: number; idIsExplicit: boolean }
            > = {};
            for (const [moduleId, loc] of sourceLocationMap) {
                sourceLocationRecord[moduleId] = loc;
            }

            // Convert interpolation resolutions Map to Record for IPC serialization
            const interpolationResolutionsRecord: Record<string, any[]> = {};
            for (const [key, resolutions] of interpolationResolutions) {
                interpolationResolutionsRecord[key] = resolutions;
            }

            // Convert call site spans Map to Record for IPC serialization
            const callSiteSpansRecord: Record<
                string,
                { startLine: number; endLine: number }
            > = {};
            for (const [key, span] of callSiteSpans) {
                callSiteSpansRecord[key] = span;
            }

            // Requirement: assume a full change when a different file/buffer is evaluated.
            const shouldReconcile =
                Boolean(sourceId) && lastAppliedSourceId === sourceId;

            if (DEBUG_LOG) {
                if (!sourceId) {
                    console.log(
                        '[patch-remap] no sourceId; reconciliation disabled',
                    );
                } else if (!shouldReconcile) {
                    console.log(
                        `[patch-remap] source changed (${lastAppliedSourceId ?? 'none'} -> ${sourceId}); reconciliation disabled`,
                    );
                } else {
                    console.log(
                        `[patch-remap] reconciling for sourceId=${sourceId}`,
                    );
                }
            }

            const { moduleIdRemap } = reconcilePatchBySimilarity(
                patch,
                shouldReconcile ? lastAppliedPatchGraph : null,
                {
                    ambiguityMargin: PATCH_REMAP_MARGIN,
                    debugLog: DEBUG_LOG
                        ? (message) => console.log(message)
                        : undefined,
                    matchThreshold: PATCH_REMAP_THRESHOLD,
                },
            );

            if (DEBUG_LOG) {
                const remapCount = Object.keys(moduleIdRemap).length;
                const thresholdInfo =
                    PATCH_REMAP_THRESHOLD !== undefined
                        ? PATCH_REMAP_THRESHOLD.toFixed(4)
                        : 'default';
                const marginInfo =
                    PATCH_REMAP_MARGIN !== undefined
                        ? PATCH_REMAP_MARGIN.toFixed(4)
                        : 'default';
                console.log(
                    `[patch-remap] summary shouldReconcile=${shouldReconcile} remaps=${remapCount} threshold=${thresholdInfo} margin=${marginInfo}`,
                );
            }

            // Send remap hints along with the desired patch
            patch.moduleIdRemaps = Object.entries(moduleIdRemap).map(
                ([from, to]) => ({
                    from,
                    to,
                }),
            );

            const { errors, updateId } = synth.updatePatch(patch, trigger);

            if (errors.length === 0) {
                lastAppliedPatchGraph = patch;
                lastAppliedSourceId = sourceId ?? null;
            }

            if (errors.length > 0) {
                return {
                    appliedPatch: patch,
                    callSiteSpans: callSiteSpansRecord,
                    errors,
                    interpolationResolutions: interpolationResolutionsRecord,
                    moduleIdRemap,
                    sliders,
                    sourceLocationMap: sourceLocationRecord,
                    success: false,
                    updateId,
                };
            }

            return {
                appliedPatch: patch,
                callSiteSpans: callSiteSpansRecord,
                errors: [],
                interpolationResolutions: interpolationResolutionsRecord,
                moduleIdRemap,
                sliders,
                sourceLocationMap: sourceLocationRecord,
                success: true,
                updateId,
            };
        } catch (error) {
            const errorMessage =
                error instanceof Error ? error.message : String(error);
            return {
                errorMessage,
                success: false,
            };
        }
    },
);

registerIPCHandler('SYNTH_GET_SAMPLE_RATE', () => synth.sampleRate());

registerIPCHandler('SYNTH_GET_CHANNELS', () => synth.channels());

registerIPCHandler('SYNTH_GET_SCOPES', () => synth.getScopes());

registerIPCHandler('SYNTH_GET_MODULE_STATES', () => synth.getModuleStates());

registerIPCHandler('GET_MINI_LEAF_SPANS', (source) => getMiniLeafSpans(source));

registerIPCHandler('SYNTH_UPDATE_PATCH', (patch, sourceId, trigger) => {
    // Requirement: assume a full change when a different file/buffer is evaluated.
    const shouldReconcile =
        Boolean(sourceId) && lastAppliedSourceId === sourceId;

    if (DEBUG_LOG) {
        if (!sourceId) {
            console.log('[patch-remap] no sourceId; reconciliation disabled');
        } else if (!shouldReconcile) {
            console.log(
                `[patch-remap] source changed (${lastAppliedSourceId ?? 'none'} -> ${sourceId}); reconciliation disabled`,
            );
        } else {
            console.log(`[patch-remap] reconciling for sourceId=${sourceId}`);
        }
    }

    const { moduleIdRemap } = reconcilePatchBySimilarity(
        patch,
        shouldReconcile ? lastAppliedPatchGraph : null,
        {
            ambiguityMargin: PATCH_REMAP_MARGIN,
            debugLog: DEBUG_LOG ? (message) => console.log(message) : undefined,
            matchThreshold: PATCH_REMAP_THRESHOLD,
        },
    );

    if (DEBUG_LOG) {
        const remapCount = Object.keys(moduleIdRemap).length;
        const thresholdInfo =
            PATCH_REMAP_THRESHOLD !== undefined
                ? PATCH_REMAP_THRESHOLD.toFixed(4)
                : 'default';
        const marginInfo =
            PATCH_REMAP_MARGIN !== undefined
                ? PATCH_REMAP_MARGIN.toFixed(4)
                : 'default';
        console.log(
            `[patch-remap] summary shouldReconcile=${shouldReconcile} remaps=${remapCount} threshold=${thresholdInfo} margin=${marginInfo}`,
        );
    }

    // Send remap hints along with the desired patch; Rust will use them to
    // Preserve module instances while keeping the desired ids.
    patch.moduleIdRemaps = Object.entries(moduleIdRemap).map(([from, to]) => ({
        from,
        to,
    }));

    const { errors, updateId } = synth.updatePatch(patch, trigger);

    if (errors.length === 0) {
        lastAppliedPatchGraph = patch;
        lastAppliedSourceId = sourceId ?? null;
    }

    return { appliedPatch: patch, errors, moduleIdRemap, updateId };
});

registerIPCHandler('SYNTH_START_RECORDING', (filePath) =>
    synth.startRecording(filePath),
);

registerIPCHandler('SYNTH_STOP_RECORDING', () => synth.stopRecording());

registerIPCHandler('SYNTH_IS_RECORDING', () => synth.isRecording());

registerIPCHandler('SYNTH_GET_HEALTH', () => synth.getHealth());

registerIPCHandler('SYNTH_STOP', () => {
    synth.stop();
});

registerIPCHandler('SYNTH_IS_STOPPED', () => synth.isStopped());

registerIPCHandler('SYNTH_SET_MODULE_PARAM', (moduleId, moduleType, params) => {
    synth.setModuleParam(moduleId, moduleType, params);
});

registerIPCHandler('SYNTH_GET_TRANSPORT_STATE', () =>
    synth.getTransportState(),
);

// Audio device operations - new API
registerIPCHandler('AUDIO_REFRESH_DEVICE_CACHE', () => {
    synth.refreshDeviceCache();
});

registerIPCHandler('AUDIO_GET_DEVICE_CACHE', () => synth.getDeviceCache());

registerIPCHandler('AUDIO_GET_CURRENT_STATE', () =>
    synth.getCurrentAudioState(),
);

registerIPCHandler(
    'AUDIO_RECREATE_STREAMS',
    (
        outputDeviceId: string,
        sampleRate: number,
        bufferSize: number | null,
        inputDeviceId: string | null,
    ) => {
        synth.recreateStreams(
            outputDeviceId,
            sampleRate,
            bufferSize ?? undefined,
            inputDeviceId ?? undefined,
        );
        saveAudioConfig();
    },
);

// Legacy audio device operations (for backward compatibility)
registerIPCHandler('AUDIO_REFRESH_DEVICE_LIST', () => {
    synth.refreshDeviceList();
});

registerIPCHandler('AUDIO_LIST_HOSTS', () => synth.listAudioHosts());

registerIPCHandler('AUDIO_LIST_OUTPUT_DEVICES', () =>
    synth.listAudioOutputDevices(),
);

registerIPCHandler('AUDIO_LIST_INPUT_DEVICES', () =>
    synth.listAudioInputDevices(),
);

registerIPCHandler('AUDIO_GET_OUTPUT_DEVICE', () => synth.getOutputDeviceId());

registerIPCHandler('AUDIO_GET_INPUT_DEVICE', () => synth.getInputDeviceId());

registerIPCHandler('AUDIO_SET_OUTPUT_DEVICE', (deviceId: string) => {
    synth.setAudioOutputDevice(deviceId);
    saveAudioConfig();
});

registerIPCHandler('AUDIO_SET_INPUT_DEVICE', (deviceId: string | null) => {
    synth.setAudioInputDevice(deviceId ?? undefined);
    saveAudioConfig();
});

registerIPCHandler('AUDIO_GET_INPUT_CHANNELS', () => synth.inputChannels());

// MIDI device operations
registerIPCHandler('MIDI_LIST_INPUTS', () => synth.listMidiInputs());

registerIPCHandler('MIDI_GET_INPUT', () => synth.getMidiInputName());

registerIPCHandler('MIDI_SET_INPUT', (portName: string | null) => {
    synth.setMidiInput(portName ?? undefined);
});

registerIPCHandler('MIDI_TRY_RECONNECT', () => {
    synth.tryReconnectMidi();
});

registerIPCHandler('SHOW_CONTEXT_MENU', (options: ContextMenuOptions) => {
    // We import Menu, MenuItem dynamically or assume they are available if imported at top
    // Since imports are top-level, we can use them.
    const menu = new Menu();
    const webContents = BrowserWindow.getAllWindows()[0]?.webContents;

    if (!webContents) {
        return;
    }

    if (options.type === 'untitled') {
        menu.append(
            new MenuItem({
                click: () =>
                    webContents.send(IPC_CHANNELS.ON_CONTEXT_MENU_COMMAND, {
                        command: 'save',
                        bufferId: options.bufferId,
                    }),
                label: 'Save',
            }),
        );
    } else if (options.type === 'file' || options.type === 'directory') {
        const filePath = options.path;

        if (options.type === 'file') {
            if (options.isOpenBuffer) {
                menu.append(
                    new MenuItem({
                        click: () =>
                            webContents.send(
                                IPC_CHANNELS.ON_CONTEXT_MENU_COMMAND,
                                { command: 'save', bufferId: options.bufferId },
                            ),
                        label: 'Save',
                    }),
                );
                menu.append(new MenuItem({ type: 'separator' }));
            }
        }

        menu.append(
            new MenuItem({
                click: () =>
                    webContents.send(IPC_CHANNELS.ON_CONTEXT_MENU_COMMAND, {
                        command: 'rename',
                        path: options.path,
                        bufferId: options.bufferId,
                    }),
                label: 'Rename...',
            }),
        );

        menu.append(
            new MenuItem({
                click: () =>
                    webContents.send(IPC_CHANNELS.ON_CONTEXT_MENU_COMMAND, {
                        command: 'delete',
                        path: options.path,
                        bufferId: options.bufferId,
                    }),
                label: 'Delete',
            }),
        );

        menu.append(new MenuItem({ type: 'separator' }));
        menu.append(
            new MenuItem({
                click: () => {
                    if (filePath) {
                        const absPath = validatePathInWorkspace(filePath);
                        if (absPath) shell.showItemInFolder(absPath);
                    }
                },
                label: 'Reveal in Finder/Explorer',
            }),
        );
    }

    menu.popup();
});

// Filesystem IPC handlers
// @ts-expect-error - async handler returns Promise
registerIPCHandler('FS_SELECT_WORKSPACE', async () => {
    const properties: Electron.OpenDialogOptions['properties'] = [
        'openDirectory',
    ];

    // Add 'createDirectory' for macOS or 'promptToCreate' for Windows if needed
    if (process.platform === 'darwin') {
        properties.push('createDirectory'); // Allows creating new directories from the dialog on macOS
    } else if (process.platform === 'win32') {
        // Note: promptToCreate on Windows prompts for creation if the path doesn't exist,
        // But doesn't handle the actual creation, which must be done by your app.
        properties.push('promptToCreate');
    }
    const result = await dialog.showOpenDialog({
        properties,
    });

    if (result.canceled || result.filePaths.length === 0) {
        return null;
    }

    currentWorkspaceRoot = result.filePaths[0];
    console.log('Workspace selected:', currentWorkspaceRoot);

    // Save to config (load-merge-save to preserve other settings)
    const config = loadConfig();
    config.lastOpenedFolder = currentWorkspaceRoot;
    saveConfig(config);

    return { path: currentWorkspaceRoot };
});

registerIPCHandler('FS_GET_WORKSPACE', () =>
    currentWorkspaceRoot ? { path: currentWorkspaceRoot } : null,
);

registerIPCHandler('FS_LIST_FILES', () => {
    if (!currentWorkspaceRoot) {
        return [];
    }
    return buildFileTree(currentWorkspaceRoot);
});

registerIPCHandler('FS_READ_FILE', (relativePath) => {
    const absolutePath = validatePathInWorkspace(relativePath);
    if (!absolutePath) {
        throw new Error('Invalid file path or no workspace selected');
    }

    try {
        return fs.readFileSync(absolutePath, 'utf-8');
    } catch (error) {
        console.error('Error reading file:', error);
        throw new Error(`Failed to read file: ${relativePath}`, {
            cause: error,
        });
    }
});

registerIPCHandler('FS_WRITE_FILE', (relativePath, content) => {
    const absolutePath = validatePathInWorkspace(relativePath);
    if (!absolutePath) {
        return {
            error: 'Invalid file path or no workspace selected',
            success: false,
        };
    }

    try {
        // Ensure directory exists
        const dir = path.dirname(absolutePath);
        if (!fs.existsSync(dir)) {
            fs.mkdirSync(dir, { recursive: true });
        }

        fs.writeFileSync(absolutePath, content, 'utf-8');
        return { success: true };
    } catch (error) {
        console.error('Error writing file:', error);
        return {
            error: `Failed to write file: ${relativePath}`,
            success: false,
        };
    }
});

registerIPCHandler('FS_RENAME_FILE', (oldPath, newPath) => {
    const oldAbsolutePath = validatePathInWorkspace(oldPath);
    const newAbsolutePath = validatePathInWorkspace(newPath);

    if (!oldAbsolutePath || !newAbsolutePath) {
        return {
            error: 'Invalid file path or no workspace selected',
            success: false,
        };
    }

    try {
        // Ensure target directory exists
        const dir = path.dirname(newAbsolutePath);
        if (!fs.existsSync(dir)) {
            fs.mkdirSync(dir, { recursive: true });
        }

        // Check for collision
        if (fs.existsSync(newAbsolutePath)) {
            // Check if it's the same file (e.g. case-only rename on case-insensitive FS)
            try {
                const oldStat = fs.statSync(oldAbsolutePath);
                const newStat = fs.statSync(newAbsolutePath);
                // If inodes coincide, it's the same file, so allow rename (case change)
                if (oldStat.ino !== newStat.ino) {
                    return {
                        error: 'A file with that name already exists.',
                        success: false,
                    };
                }
            } catch {
                // If we can't verify, be safe and prevent overwrite
                return {
                    error: 'A file with that name already exists.',
                    success: false,
                };
            }
        }

        fs.renameSync(oldAbsolutePath, newAbsolutePath);
        return { success: true };
    } catch (error) {
        console.error('Error renaming file:', error);
        return { error: `Failed to rename file: ${oldPath}`, success: false };
    }
});

registerIPCHandler('FS_DELETE_FILE', async (absolutePath) => {
    try {
        await shell.trashItem(absolutePath);
        return { success: true };
    } catch (error) {
        console.error('Error deleting file:', error);
        return { error: `Failed to delete: ${absolutePath}`, success: false };
    }
});

registerIPCHandler('FS_MOVE_FILE', (sourcePath, destPath) => {
    const sourceAbsolutePath = validatePathInWorkspace(sourcePath);
    const destAbsolutePath = validatePathInWorkspace(destPath);

    if (!sourceAbsolutePath || !destAbsolutePath) {
        return {
            error: 'Invalid file path or no workspace selected',
            success: false,
        };
    }

    try {
        // Ensure target directory exists
        const dir = path.dirname(destAbsolutePath);
        if (!fs.existsSync(dir)) {
            fs.mkdirSync(dir, { recursive: true });
        }

        fs.renameSync(sourceAbsolutePath, destAbsolutePath);
        return { success: true };
    } catch (error) {
        console.error('Error moving file:', error);
        return { error: `Failed to move file: ${sourcePath}`, success: false };
    }
});

registerIPCHandler('FS_CREATE_FOLDER', (relativePath) => {
    const absolutePath = validatePathInWorkspace(relativePath);
    if (!absolutePath) {
        return {
            error: 'Invalid folder path or no workspace selected',
            success: false,
        };
    }

    try {
        fs.mkdirSync(absolutePath, { recursive: true });
        return { success: true };
    } catch (error) {
        console.error('Error creating folder:', error);
        return {
            error: `Failed to create folder: ${relativePath}`,
            success: false,
        };
    }
});

// @ts-expect-error - async handler returns Promise
registerIPCHandler('FS_SHOW_SAVE_DIALOG', async (defaultPath?: string) => {
    console.log('defaultPath:', defaultPath);
    const result = await dialog.showSaveDialog({
        defaultPath: defaultPath || 'untitled.mjs',
        filters: [
            { extensions: ['js', 'mjs'], name: 'JavaScript Files' },
            { extensions: ['*'], name: 'All Files' },
        ],
    });

    if (result.canceled || !result.filePath) {
        return null;
    }

    // Return relative path if within workspace, otherwise absolute
    if (
        currentWorkspaceRoot &&
        result.filePath.startsWith(currentWorkspaceRoot)
    ) {
        return path.relative(currentWorkspaceRoot, result.filePath);
    }

    return result.filePath;
});

registerIPCHandler(
    'FS_SHOW_INPUT_DIALOG',
    // @ts-expect-error - async handler returns Promise
    async (title: string, defaultValue?: string) => {
        // Electron doesn't have a built-in input dialog, so we'll use a save dialog for now
        // A proper implementation would create a custom BrowserWindow with a form
        const result = await dialog.showSaveDialog({
            defaultPath: defaultValue || '',
            filters: [
                { name: 'JavaScript Files', extensions: ['js', 'mjs'] },
                { name: 'All Files', extensions: ['*'] },
            ],
            title,
        });

        if (result.canceled || !result.filePath) {
            return null;
        }

        // Return just the filename for rename operations
        return path.basename(result.filePath);
    },
);

registerIPCHandler('SHOW_UNSAVED_CHANGES_DIALOG', async (fileName: string) => {
    const result = await dialog.showMessageBox({
        type: 'warning',
        buttons: ['Save', "Don't Save", 'Cancel'],
        defaultId: 0, // Save is default (primary)
        cancelId: 2, // Cancel
        message: `Do you want to save the changes you made to ${fileName}?`,
        detail: "Your changes will be lost if you don't save them.",
    });

    return result.response; // Returns the button index: 0=Save, 1=Don't Save, 2=Cancel
});

let helpWindow: BrowserWindow | null = null;

const createHelpWindow = () => {
    if (helpWindow) {
        helpWindow.focus();
        return;
    }

    helpWindow = new BrowserWindow({
        height: 1000,
        title: 'Operator Help',
        webPreferences: {
            preload: path.join(__dirname, 'preload.js'),
        },
        width: 1500,
    });

    // Load the index.html of the app with #help hash
    if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
        void helpWindow.loadURL(MAIN_WINDOW_VITE_DEV_SERVER_URL + '#help');
    } else {
        void helpWindow.loadFile(
            path.join(
                __dirname,
                `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html`,
            ),
            { hash: 'help' },
        );
    }

    helpWindow.on('closed', () => {
        helpWindow = null;
    });
};

registerIPCHandler('OPEN_HELP_WINDOW', async () => {
    createHelpWindow();
});

registerIPCHandler(
    'OPEN_HELP_FOR_SYMBOL',
    async (symbolType: 'type' | 'module' | 'namespace', symbolName: string) => {
        createHelpWindow();
        // Send navigation message to help window after it loads
        if (helpWindow) {
            helpWindow.webContents.once('did-finish-load', () => {
                helpWindow?.webContents.send('navigate-to-symbol', {
                    symbolName,
                    symbolType,
                });
            });
            // If already loaded, send immediately
            if (!helpWindow.webContents.isLoading()) {
                helpWindow.webContents.send('navigate-to-symbol', {
                    symbolName,
                    symbolType,
                });
            }
        }
    },
);

// Config IPC handlers
registerIPCHandler('CONFIG_GET_PATH', () => {
    ensureConfigExists();
    return CONFIG_FILE;
});

registerIPCHandler('CONFIG_READ', () => {
    ensureConfigExists();
    return loadConfig();
});

registerIPCHandler('CONFIG_WRITE', (partial: Partial<AppConfig>) => {
    ensureConfigExists();
    const current = loadConfig();
    const merged = { ...current, ...partial };
    saveConfig(merged);
});

// Update operations
ipcMain.handle(IPC_CHANNELS.UPDATE_CHECK, async () => {
    await checkForUpdateAvailability();
});

ipcMain.handle(IPC_CHANNELS.UPDATE_DOWNLOAD, () => {
    if (!supportsAutoUpdater) {
        if (latestReleaseUrl) {
            void shell.openExternal(latestReleaseUrl);
        }
        return;
    }
    sendUpdateEvent(IPC_CHANNELS.UPDATE_DOWNLOADING);
    autoUpdater.checkForUpdates();
});

ipcMain.handle(IPC_CHANNELS.UPDATE_INSTALL, () => {
    if (!supportsAutoUpdater) {
        return;
    }
    autoUpdater.quitAndInstall();
});

/**
 * Create the main application window
 */
const createWindow = (): void => {
    const isMac = process.platform === 'darwin';

    // Create the browser window.
    mainWindow = new BrowserWindow({
        height: 1000,
        titleBarStyle: isMac ? 'hiddenInset' : 'default',
        trafficLightPosition: isMac ? { x: 12, y: 10 } : undefined,
        webPreferences: {
            preload: path.join(__dirname, 'preload.js'),
        },
        width: 1500,
    });

    // Quit app when window is closed (on all platforms, including macOS)
    mainWindow.on('close', () => {
        app.quit();
    });

    // And load the index.html of the app.
    if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
        void mainWindow.loadURL(MAIN_WINDOW_VITE_DEV_SERVER_URL);
    } else {
        void mainWindow.loadFile(
            path.join(
                __dirname,
                `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html`,
            ),
        );
    }

    // Flush pending logs when the renderer is ready
    mainWindow.webContents.on('did-finish-load', () => {
        flushPendingLogs();
    });

    // Start watching config file for changes
    startConfigWatcher();
};

/**
 * Create the application menu
 */
const createMenu = (): void => {
    const isMac = process.platform === 'darwin';

    const template: Electron.MenuItemConstructorOptions[] = [
        // App menu (macOS only)
        ...(isMac
            ? ([
                  {
                      label: app.name,
                      submenu: [
                          { role: 'about' },
                          { type: 'separator' },
                          {
                              click: async () => {
                                  await checkForUpdateAvailability();
                              },
                              label: 'Check for Updates...',
                          },
                          { type: 'separator' },
                          {
                              accelerator: 'Cmd+,',
                              click: () => {
                                  if (mainWindow && !mainWindow.isDestroyed()) {
                                      mainWindow.webContents.send(
                                          MENU_CHANNELS.OPEN_SETTINGS,
                                      );
                                  }
                              },
                              label: 'Settings...',
                          },
                          { type: 'separator' },
                          { role: 'services' },
                          { type: 'separator' },
                          { role: 'hide' },
                          { role: 'hideOthers' },
                          { role: 'unhide' },
                          { type: 'separator' },
                          { role: 'quit' },
                      ],
                  },
              ] satisfies Electron.MenuItemConstructorOptions[])
            : []),
        // File menu
        {
            label: 'File',
            submenu: [
                {
                    accelerator: 'CmdOrCtrl+N',
                    click: (_item, focusedWindow) => {
                        if (focusedWindow) {
                            BrowserWindow.fromId(
                                focusedWindow.id,
                            )?.webContents.send(MENU_CHANNELS.NEW_FILE);
                        }
                    },
                    label: 'New File',
                },
                {
                    accelerator: 'CmdOrCtrl+O',
                    click: (_item, focusedWindow) => {
                        if (focusedWindow) {
                            BrowserWindow.fromId(
                                focusedWindow.id,
                            )?.webContents.send(MENU_CHANNELS.OPEN_WORKSPACE);
                        }
                    },
                    label: 'Open Workspace...',
                },
                { type: 'separator' },
                {
                    accelerator: 'CmdOrCtrl+S',
                    click: (_item, focusedWindow) => {
                        if (focusedWindow) {
                            BrowserWindow.fromId(
                                focusedWindow.id,
                            )?.webContents.send(MENU_CHANNELS.SAVE);
                        }
                    },
                    label: 'Save',
                },
                {
                    accelerator: 'CmdOrCtrl+W',
                    click: (_item, focusedWindow) => {
                        if (focusedWindow) {
                            BrowserWindow.fromId(
                                focusedWindow.id,
                            )?.webContents.send(MENU_CHANNELS.CLOSE_BUFFER);
                        }
                    },
                    label: 'Close Buffer',
                },
                { type: 'separator' },
                ...(isMac
                    ? []
                    : ([
                          {
                              accelerator: 'Ctrl+,',
                              click: () => {
                                  if (mainWindow && !mainWindow.isDestroyed()) {
                                      mainWindow.webContents.send(
                                          MENU_CHANNELS.OPEN_SETTINGS,
                                      );
                                  }
                              },
                              label: 'Settings...',
                          },
                      ] satisfies Electron.MenuItemConstructorOptions[])),
                isMac ? { role: 'close' } : { role: 'quit' },
            ],
        },
        // Edit menu
        {
            label: 'Edit',
            submenu: [
                { role: 'undo' },
                { role: 'redo' },
                { type: 'separator' },
                { role: 'cut' },
                { role: 'copy' },
                { role: 'paste' },
                ...(isMac
                    ? ([
                          { role: 'pasteAndMatchStyle' },
                          { role: 'delete' },
                          { role: 'selectAll' },
                      ] satisfies Electron.MenuItemConstructorOptions[])
                    : ([
                          { role: 'delete' },
                          { type: 'separator' },
                          { role: 'selectAll' },
                      ] satisfies Electron.MenuItemConstructorOptions[])),
            ],
        },
        // View menu
        {
            role: 'viewMenu',
        },
        // Run menu
        {
            label: 'Run',
            submenu: [
                {
                    accelerator: 'Ctrl+Enter',
                    click: (_item, focusedWindow) => {
                        if (focusedWindow) {
                            BrowserWindow.fromId(
                                focusedWindow.id,
                            )?.webContents.send(MENU_CHANNELS.UPDATE_PATCH);
                        }
                    },
                    label: 'Update Patch',
                },
                {
                    accelerator: 'Ctrl+Shift+Enter',
                    click: (_item, focusedWindow) => {
                        if (focusedWindow) {
                            BrowserWindow.fromId(
                                focusedWindow.id,
                            )?.webContents.send(
                                MENU_CHANNELS.UPDATE_PATCH_NEXT_BEAT,
                            );
                        }
                    },
                    label: 'Update Patch (Next Beat)',
                },
                {
                    accelerator: 'Ctrl+.',
                    click: (_item, focusedWindow) => {
                        if (focusedWindow) {
                            BrowserWindow.fromId(
                                focusedWindow.id,
                            )?.webContents.send(MENU_CHANNELS.STOP);
                        }
                    },
                    label: 'Stop Sound',
                },
                // { type: 'separator' },
                // {
                //     Label: 'Toggle Recording',
                //     Accelerator: 'Ctrl+R',
                //     Click: (_item, focusedWindow) => {
                //         If (focusedWindow) {
                //             BrowserWindow.fromId(
                //                 FocusedWindow.id,
                //             )?.webContents.send(MENU_CHANNELS.TOGGLE_RECORDING);
                //         }
                //     },
                // },
            ],
        },
        // Window menu
        {
            role: 'windowMenu',
        },
        // Help menu (non-macOS: includes Check for Updates)
        ...(!isMac
            ? ([
                  {
                      label: 'Help',
                      submenu: [
                          {
                              click: async () => {
                                  await checkForUpdateAvailability();
                              },
                              label: 'Check for Updates...',
                          },
                      ],
                  },
              ] satisfies Electron.MenuItemConstructorOptions[])
            : []),
    ];

    const menu = Menu.buildFromTemplate(template);
    Menu.setApplicationMenu(menu);
};

// This method will be called when Electron has finished
// Initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
    // In E2E test mode, use the workspace provided via env var
    if (process.env.E2E_WORKSPACE && fs.existsSync(process.env.E2E_WORKSPACE)) {
        currentWorkspaceRoot = process.env.E2E_WORKSPACE;
        console.log('E2E workspace:', currentWorkspaceRoot);
    } else {
        // Load last opened folder
        const config = loadConfig();
        if (config.lastOpenedFolder && fs.existsSync(config.lastOpenedFolder)) {
            currentWorkspaceRoot = config.lastOpenedFolder;
            console.log('Restored last opened folder:', currentWorkspaceRoot);
        }
    }

    // Audio configuration is already restored during Synthesizer initialization
    // (the config is passed to the constructor)

    createWindow();
    createMenu();

    if (app.isPackaged) {
        initAutoUpdater();
        // Delay first check slightly so the window is visible before a banner appears
        setTimeout(() => void checkForUpdateAvailability(), 5000);
    }

    // Dev-only: register a hotkey to restart the main process.
    // Sends SIGUSR1 to the wrapper script, which injects `rs` into forge's stdin
    // So the Vite dev server stays alive and only Electron restarts.
    if (!app.isPackaged && process.env.DEV_WRAPPER_PID) {
        globalShortcut.register('CommandOrControl+Shift+R', () => {
            console.log('[dev] Restarting main process...');
            process.kill(parseInt(process.env.DEV_WRAPPER_PID!), 'SIGUSR1');
        });
    }
});

app.on('will-quit', () => {
    globalShortcut.unregisterAll();
});

// Quit when all windows are closed (on all platforms, including macOS)
app.on('window-all-closed', () => {
    app.quit();
});

// Remove the macOS-specific reactivation behavior since we want single window only
app.on('activate', () => {
    // Prevent window recreation on macOS
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});

// In this file you can include the rest of your app's specific main process
// Code. You can also put them in separate files and import them here.
