#!/usr/bin/env node
// Build scripts/buildGrammar.mjs
//
// Compiles src/main/dsl/miniNotation/grammar.peggy into grammar.generated.ts.
// Run via `yarn build:grammar` whenever the grammar changes.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import peggy from 'peggy';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');
const grammarPath = resolve(
    repoRoot,
    'src/main/dsl/miniNotation/grammar.peggy',
);
const outputPath = resolve(
    repoRoot,
    'src/main/dsl/miniNotation/grammar.generated.ts',
);

const grammarSrc = readFileSync(grammarPath, 'utf8');

const parserSrc = peggy.generate(grammarSrc, {
    output: 'source',
    format: 'es',
    cache: false,
    optimize: 'speed',
});

const header = `/* eslint-disable */
// @ts-nocheck
// This file is generated by scripts/buildGrammar.mjs from
// src/main/dsl/miniNotation/grammar.peggy. Do not edit by hand — run
// \`yarn build:grammar\` to regenerate.
//
// The grammar file is licensed AGPL-3.0-or-later (derivative of strudel's
// krill.pegjs). This generated output inherits the same license.

`;

writeFileSync(outputPath, header + parserSrc, 'utf8');
console.log(`Wrote ${outputPath}`);
