/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Synthesizer {
  /** Run the audio thread with cpal */
  constructor()
  stop(): void
  isStopped(): boolean
  sampleRate(): number
  channels(): number
  getScopes(): Array<[ScopeItem, Float32Array]>
  updatePatch(patch: PatchGraph): Array<ApplyPatchError>
  startRecording(path?: string | undefined | null): string
  stopRecording(): string | null
  isRecording(): boolean
  getHealth(): AudioThreadHealthSnapshot
}

export interface ApplyPatchError {
  message: string
  errors?: Array<ValidationError>
}

export interface AudioThreadHealthSnapshot {
  patchLockMisses: number
  outputCallbackOverruns: number
  outputCallbackOverrunMaxNs: number
  outputCallbackDurationMaxNs: number
}

export declare function getSchemas(): Array<ModuleSchema>

/** Detailed validation error for patch validation */
export interface ValidationError {
  field: string
  message: string
  location?: string
}
/** Main AST node enum representing all possible elements in the Musical DSL */
export type ASTNode =
  | { type: 'FastSubsequence', elements: Array<ASTNode> }
  | { type: 'SlowSubsequence', elements: Array<ASTNode> }
  | { type: 'RandomChoice', choices: Array<ASTNode> }
  | { type: 'NumericLiteral', value: number }
  | { type: 'Rest' }

export type InterpolationCategory =  'In'|
'Out'|
'InOut';

export type InterpolationType =
  | { type: 'Linear' }
  | { type: 'Step' }
  | { type: 'Sine', category: InterpolationCategory }
  | { type: 'Quad', category: InterpolationCategory }
  | { type: 'Cubic', category: InterpolationCategory }
  | { type: 'Quart', category: InterpolationCategory }
  | { type: 'Quint', category: InterpolationCategory }
  | { type: 'Expo', category: InterpolationCategory }
  | { type: 'Circ', category: InterpolationCategory }
  | { type: 'Bounce', category: InterpolationCategory }

export interface ModuleIdRemap {
  from: string
  to: string
}

export interface ModuleSchema {
  name: string
  description: string
  paramsSchema: Record<string, unknown>
  outputs: Array<OutputSchema>
}

export interface ModuleState {
  id: string
  moduleType: string
  idIsExplicit?: boolean
  params: any
}

export interface OutputSchema {
  name: string
  description: string
  default: boolean
}

export interface PatchGraph {
  modules: Array<ModuleState>
  moduleIdRemaps?: Array<ModuleIdRemap>
  tracks: Array<TrackProxy>
  patterns: Array<PatternProgram>
  scopes: Array<Scope>
}

/** Root pattern node containing all top-level elements */
export interface PatternProgram {
  id: string
  elements: Array<ASTNode>
  seed: number
}

export interface Scope {
  item: ScopeItem
  msPerFrame: number
  triggerThreshold?: number
}

export type ScopeItem =
  | { type: 'ModuleOutput', moduleId: string, portName: string }
  | { type: 'Track', trackId: string }

export interface TrackKeyframeProxy {
  id: string
  trackId: string
  /** Normalized time in the range [0.0, 1.0] */
  time: number
  signal: any
}

export interface TrackProxy {
  id: string
  /** Parameter controlling the playhead position in the range [-5.0, 5.0] */
  playhead: any
  /** Interpolation type applied to all keyframes in this track */
  interpolationType: InterpolationType
  keyframes: Array<TrackKeyframeProxy>
}

/** Represents the output value from the runner */
export type Value =
  | { type: 'Numeric', field0: number }
  | { type: 'Rest' }
