import { app, BrowserWindow, ipcMain } from 'electron';
import { getSchemas, Synthesizer } from '@modular/core';
import { IPC_CHANNELS, IPCHandlers, IPCRequest, IPCResponse, Promisify } from './ipcTypes';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// Initialize the synthesizer instance
console.log('Initializing Synthesizer...');
const synth = new Synthesizer();

/**
 * Type-safe IPC handler registration
 */
function registerIPCHandler<T extends keyof typeof IPC_CHANNELS>(
  channel: T,
  handler: IPCHandlers[typeof IPC_CHANNELS[T]]
) {
  ipcMain.handle(IPC_CHANNELS[channel], async (_event, request) => {
    try {
      return handler(request);
    } catch (error) {
      console.error(`Error in IPC handler ${channel}:`, error);
      throw error;
    }
  });
}

// Register all IPC handlers
registerIPCHandler('GET_SCHEMAS', () => {
  return getSchemas();
});

registerIPCHandler('SYNTH_GET_SAMPLE_RATE', () => {
  return synth.sampleRate();
});

registerIPCHandler('SYNTH_GET_CHANNELS', () => {
  return synth.channels();
});

registerIPCHandler('SYNTH_GET_SCOPES', () => {
  return synth.getScopes();
});

registerIPCHandler('SYNTH_ADD_SCOPE', (scope) => {
  synth.addScope(scope);
});

registerIPCHandler('SYNTH_REMOVE_SCOPE', (scope) => {
  return synth.removeScope(scope);
});

registerIPCHandler('SYNTH_UPDATE_PATCH', (patch) => {
  return synth.updatePatch(patch);
});

registerIPCHandler('SYNTH_START_RECORDING', (path) => {
  return synth.startRecording(path);
});

registerIPCHandler('SYNTH_STOP_RECORDING', () => {
  return synth.stopRecording();
});

registerIPCHandler('SYNTH_IS_RECORDING', () => {
  return synth.isRecording();
});

registerIPCHandler('SYNTH_GET_HEALTH', () => {
  return synth.getHealth();
});

registerIPCHandler('SYNTH_STOP', () => {
  synth.stop();
});

registerIPCHandler('SYNTH_IS_STOPPED', () => {
  return synth.isStopped();
});

/**
 * Create the main application window
 */

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools({ mode: 'detach' });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
